### PR TITLE
Implemented basic routing and error checking in the app navigation

### PR DESCRIPTION
**Pull request by MynahMarie**
Relates #12 

In this PR I have:

- implemented routing through the front end of the app
- made sure users can't navigate the app through the url
- made sure users need to complete necessary informations before moving on to the next page.

### CODE REVIEW

**Review by MarlenAw — APPROVED** [review]

**Comment by Karyum** [comment]
@MynahMarie can i review this ? or should i wait for @hoslack ?

**Review by hoslack — APPROVED** [review]

**Comment by MynahMarie** [comment]
@Karyum Please review it... we are now working together so it might take a while for hoslack to be able to review

**Comment by Karyum** [comment]
@MynahMarie 
# Shit conflict

**Comment by MynahMarie** [comment]
@Karyum No more conflicts! 😸

**Review by Karyum — APPROVED** [review]
# hehe

**Review by Karyum — APPROVED** [review]
# Great job
but there must be a better way hmmmm

**Pull request merged**
